// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdqnwyexiratnejekuqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkcW53eWV4aXJhdG5lamVrdXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTMyMzEsImV4cCI6MjA3MDIyOTIzMX0.K7LG4lHVL9b1H8GPC8F8z_DthAPnX97CpEyKsCVqfLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});